Traceback (most recent call last):
  File "C:\Users\user\mambaforge\envs\py311\Lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\user\mambaforge\envs\py311\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\mambaforge\envs\py311\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\mambaforge\envs\py311\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\mambaforge\envs\py311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\mambaforge\envs\py311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\user\mambaforge\envs\py311\Lib\site-packages\nbclient\client.py", line 608, in async_setup_kernel
    yield
  File "C:\Users\user\mambaforge\envs\py311\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\user\mambaforge\envs\py311\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\user\mambaforge\envs\py311\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_pollutants_def.to_markdown(index = False)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [1;32m~\mambaforge\envs\py311\Lib\site-packages\pandas\compat\_optional.py:141[0m, in [0;36mimport_optional_dependency[1;34m(name, extra, errors, min_version)[0m
[0;32m    140[0m [38;5;28;01mtry[39;00m:
[1;32m--> 141[0m     module [38;5;241m=[39m [43mimportlib[49m[38;5;241;43m.[39;49m[43mimport_module[49m[43m([49m[43mname[49m[43m)[49m
[0;32m    142[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:

File [1;32m~\mambaforge\envs\py311\Lib\importlib\__init__.py:126[0m, in [0;36mimport_module[1;34m(name, package)[0m
[0;32m    125[0m         level [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[1;32m--> 126[0m [38;5;28;01mreturn[39;00m [43m_bootstrap[49m[38;5;241;43m.[39;49m[43m_gcd_import[49m[43m([49m[43mname[49m[43m[[49m[43mlevel[49m[43m:[49m[43m][49m[43m,[49m[43m [49m[43mpackage[49m[43m,[49m[43m [49m[43mlevel[49m[43m)[49m

File [1;32m<frozen importlib._bootstrap>:1206[0m, in [0;36m_gcd_import[1;34m(name, package, level)[0m

File [1;32m<frozen importlib._bootstrap>:1178[0m, in [0;36m_find_and_load[1;34m(name, import_)[0m

File [1;32m<frozen importlib._bootstrap>:1142[0m, in [0;36m_find_and_load_unlocked[1;34m(name, import_)[0m

[1;31mModuleNotFoundError[0m: No module named 'tabulate'

During handling of the above exception, another exception occurred:

[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[6], line 1[0m
[1;32m----> 1[0m [43mdf_pollutants_def[49m[38;5;241;43m.[39;49m[43mto_markdown[49m[43m([49m[43mindex[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m

File [1;32m~\mambaforge\envs\py311\Lib\site-packages\pandas\core\frame.py:2842[0m, in [0;36mDataFrame.to_markdown[1;34m(self, buf, mode, index, storage_options, **kwargs)[0m
[0;32m   2840[0m kwargs[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mtablefmt[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mpipe[39m[38;5;124m"[39m)
[0;32m   2841[0m kwargs[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mshowindex[39m[38;5;124m"[39m, index)
[1;32m-> 2842[0m tabulate [38;5;241m=[39m [43mimport_optional_dependency[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mtabulate[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m   2843[0m result [38;5;241m=[39m tabulate[38;5;241m.[39mtabulate([38;5;28mself[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   2844[0m [38;5;28;01mif[39;00m buf [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

File [1;32m~\mambaforge\envs\py311\Lib\site-packages\pandas\compat\_optional.py:144[0m, in [0;36mimport_optional_dependency[1;34m(name, extra, errors, min_version)[0m
[0;32m    142[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[0;32m    143[0m     [38;5;28;01mif[39;00m errors [38;5;241m==[39m [38;5;124m"[39m[38;5;124mraise[39m[38;5;124m"[39m:
[1;32m--> 144[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg)
[0;32m    145[0m     [38;5;28;01melse[39;00m:
[0;32m    146[0m         [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m

[1;31mImportError[0m: Missing optional dependency 'tabulate'.  Use pip or conda to install tabulate.
ImportError: Missing optional dependency 'tabulate'.  Use pip or conda to install tabulate.

